version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    container_name: viral-game-network-app
    restart: always
    depends_on:
      - cache
      - store
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - viral-game-network
  cache:
    image: redis:6.2-alpine
    env_file:
      - .env
    container_name: viral-game-network-cache-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - viral-game-network-cache:/data
    networks:
      - viral-game-network
  store:
    image: surrealdb/surrealdb:latest
    env_file:
      - .env
    container_name: viral-game-network-store-surrealdb
    restart: always
    command: start --user=${STORE_USERNAME} --pass=${STORE_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - viral-game-network-store:/data
    networks:
      - viral-game-network
  registry:
    image: registry:latest
    env_file:
      - .env
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    container_name: viral-game-network-registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - viral-game-network-registry:/data
    networks:
      - viral-game-network
volumes:
  viral-game-network-cache:
    driver: local
  viral-game-network-store:
    driver: local
  viral-game-network-registry:
    driver: local
networks:
  viral-game-network:
    external: true